h05927
s 00022/00000/00000
d D 1.1 94/11/18 01:26:35 lm 2 1
c Initial revision
cC
e
s 00000/00000/00000
d D 1.0 94/11/18 01:26:34 lm 1 0
cHlm.bitmover.com
cPdoc/lat_syscall.8
cRb18bb8295c98aaf1
cZ-08:00
c______________________________________________________________________
e
u
U
f e 0
f b
f x 34
t
lmbench doc checkin
T
I 2
.\" $Id$
.TH LAT_SYSCALL 8 "$Date$" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_syscall - time simple entry into the operating system
.SH SYNOPSIS
.B lat_syscall
.SH DESCRIPTION
.B lat_syscall
times how long it takes to write one byte to \f(CB/dev/null\fP.  This
is useful as a lower bound cost on anything that has to interact with
the operating system.
.SH OUTPUT
Output format is 
.sp
.ft CB
Null syscall: 67 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8).
E 2
