.\" $Id: s.lat_syscall.8 1.1 94/11/18 01:26:35-08:00 lm@lm.bitmover.com $
.TH LAT_SYSCALL 8 "$Date: 94/11/18 01:26:35-08:00 $" "(c)1994 Larry McVoy" "LMBENCH"
.SH NAME
lat_syscall - time simple entry into the operating system
.SH SYNOPSIS
.B lat_syscall
.SH DESCRIPTION
.B lat_syscall
times how long it takes to write one byte to \f(CB/dev/null\fP.  This
is useful as a lower bound cost on anything that has to interact with
the operating system.
.SH OUTPUT
Output format is 
.sp
.ft CB
Null syscall: 67 microseconds
.ft
.SH ACKNOWLEDGEMENT
Funding for the development of
this tool was provided by Sun Microsystems Computer Corporation.
.SH "SEE ALSO"
lmbench(8).
